# benchmark config yaml
### Please fill these accordingly
data_dir: /home/kwu/dataset/50G/parquet_1gb 
output_dir: ./
file_format: parquet
output_filetype: parquet
split_row_groups: False
repartition_small_table: True
benchmark_runner_include_bsql: False

scheduler_file_path: 
dask_profile: False
dask_dir: ./
num_workers: 1

verify_results: False
verify_dir: 

sheet: GPU-BDB
tab: SF1000 Benchmarking Matrix
get_read_time: False
cluster_host: 127.0.0.1
